-- Rate-limit the guest table search, so the roster stops being enumerable.
--
-- Measured before writing this, with the anon key: 141 two-letter queries
-- recovered 14 of 116 seated guests together with their table names. The
-- `limit 5` holds per call, but nothing limited the number of calls, so the
-- whole seating plan was recoverable in a few thousand requests. That defeats
-- cahier §16, whose point is that the list must not be enumerable.
--
-- Why in the database rather than in front of it: the RPC is the only path to
-- guest data, and it is reachable directly with the anon key — not just
-- through our own page. A limit in the Next.js action would be trivially
-- bypassed by calling PostgREST. Putting it inside the security-definer
-- function means every caller is counted, including one we did not write.
--
-- The four original guarantees are untouched: 2-character minimum, 5-row cap,
-- confirmed AND seated only, and four columns. This migration only adds a
-- fifth condition in front of them.

create table if not exists public.guest_search_attempts (
  id bigint generated by default as identity primary key,
  wedding_id uuid references public.weddings(id) on delete cascade not null,
  -- No IP address and no fingerprint: we cannot see the client's IP from
  -- inside Postgres, and inventing an identifier would mean logging something
  -- about a guest who has done nothing wrong. The window is therefore
  -- per-wedding, which is the unit that actually needs protecting.
  searched_at timestamptz default timezone('utc'::text, now()) not null
);

comment on table public.guest_search_attempts is
  'One row per search_guest_table call, used only to enforce a per-wedding '
  'rate limit. Holds no query text, no IP, and nothing about the person '
  'searching — a guest looking for their own table is not a suspect.';

create index if not exists idx_guest_search_attempts_window
  on public.guest_search_attempts(wedding_id, searched_at desc);

alter table public.guest_search_attempts enable row level security;

-- No policy at all: only the security-definer function touches this table, and
-- it bypasses RLS. Anonymous callers must not be able to read the log or to
-- clear it by deleting rows.

/**
 * The rate limit itself, split out so it can be reasoned about on its own.
 *
 * 30 searches per wedding per 10 minutes. A real guest types a few letters,
 * finds their table and stops — the debounced page sends one request per
 * search, so a whole family sharing a phone stays far under it. An enumeration
 * run needs thousands of queries and hits the wall in seconds.
 *
 * Returns true when the call is allowed, and records it.
 */
create or replace function public.check_guest_search_rate(p_wedding_id uuid)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  v_recent int;
begin
  select count(*) into v_recent
  from public.guest_search_attempts
  where wedding_id = p_wedding_id
    and searched_at > now() - interval '10 minutes';

  if v_recent >= 30 then
    return false;
  end if;

  insert into public.guest_search_attempts (wedding_id) values (p_wedding_id);

  -- Opportunistic cleanup: drop rows older than the window on roughly one call
  -- in twenty, so the table cannot grow without bound and no cron job is
  -- needed. Cheap because of the index above.
  if random() < 0.05 then
    delete from public.guest_search_attempts
    where searched_at < now() - interval '1 hour';
  end if;

  return true;
end;
$$;

revoke all on function public.check_guest_search_rate(uuid) from public;
-- Not granted to anon: only the search function calls it, and that one is
-- security definer, so it runs with the owner's rights.

/**
 * `search_guest_table`, with the rate limit in front.
 *
 * Everything below the rate check is the original function, unchanged —
 * same 2-character minimum, same accent folding, same confirmed+seated
 * filter, same four columns, same `limit 5`. Do not relax any of them
 * without re-reading cahier §16 (see the warning in README-step-2.md).
 */
create or replace function public.search_guest_table(p_wedding_id uuid, p_query text)
returns table (
  first_name text,
  last_name text,
  table_name text,
  seats_label text
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_query text;
begin
  if p_wedding_id is null or length(trim(p_query)) < 2 then
    return;
  end if;

  -- Refuse once the window is full. Returning empty rather than raising keeps
  -- the guest page's UX simple, and tells an enumerator nothing about why.
  if not public.check_guest_search_rate(p_wedding_id) then
    return;
  end if;

  v_query := translate(
    lower(trim(p_query)),
    'àâäéèêëïîôöùûüçñÀÂÄÉÈÊËÏÎÔÖÙÛÜÇÑ',
    'aaaeeeeiioouuucnAAAEEEEIIOOUUUCN'
  );

  return query
  select
    g.first_name,
    g.last_name,
    t.name as table_name,
    t.seats_label
  from public.guests g
  join public.tables t on t.id = g.table_id
  where g.wedding_id = p_wedding_id
    and g.status = 'confirmed'
    and g.table_id is not null
    and (
      translate(lower(g.first_name), 'àâäéèêëïîôöùûüçñÀÂÄÉÈÊËÏÎÔÖÙÛÜÇÑ', 'aaaeeeeiioouuucnAAAEEEEIIOOUUUCN') like '%' || v_query || '%'
      or translate(lower(g.last_name), 'àâäéèêëïîôöùûüçñÀÂÄÉÈÊËÏÎÔÖÙÛÜÇÑ', 'aaaeeeeiioouuucnAAAEEEEIIOOUUUCN') like '%' || v_query || '%'
    )
  order by g.last_name, g.first_name
  limit 5;
end;
$$;

comment on function public.search_guest_table(uuid, text) is
  'Security-definer RPC backing the Jour J "Ma table" search. The only path by '
  'which an anonymous guest can query the guest list: confirmed+seated only, a '
  '2-character minimum, a 5-row cap, four columns (no contact info, no status, '
  'no id), and since 20260903110000 a limit of 30 searches per wedding per 10 '
  'minutes so the list cannot be enumerated by volume. Do not relax any of '
  'these without re-reading cahier des charges §16.';
