-- Public contact form: message storage plus the anti-spam limits.
--
-- Why everything below lives in the database rather than in the Next.js
-- server action: `NEXT_PUBLIC_SUPABASE_ANON_KEY` is public by definition, and
-- the existing public tables (`rsvp_responses`, `playlist_suggestions`) insert
-- with `check (true)`. A bot therefore never has to touch our page — it can
-- POST straight to PostgREST, where no honeypot, no submit delay and no
-- TypeScript validation is on its path. This is the same defect that was
-- measured and fixed for the guest search in 20260903110000.
--
-- So: no insert policy at all on `contact_messages`. The only write path is
-- `submit_contact_message`, which is security definer and counts EVERY caller,
-- including one we did not write.

create table if not exists public.contact_messages (
  id uuid default gen_random_uuid() primary key,
  name text not null,
  email text not null,
  subject text not null,
  message text not null,
  locale text not null,
  status text not null default 'new',
  created_at timestamptz default timezone('utc'::text, now()) not null,

  -- Bounds as table constraints, not only inside the function: a last net if
  -- the function is ever rewritten without re-reading the design doc.
  constraint contact_messages_name_len check (char_length(name) between 1 and 80),
  constraint contact_messages_email_len check (char_length(email) between 1 and 160),
  constraint contact_messages_message_len check (char_length(message) between 10 and 2000),
  constraint contact_messages_locale_len check (char_length(locale) between 2 and 5),
  constraint contact_messages_subject_enum check (
    subject in ('avant-achat', 'ma-commande', 'technique', 'sur-mesure', 'autre')
  ),
  constraint contact_messages_status_enum check (status in ('new', 'handled'))
);

comment on table public.contact_messages is
  'Messages from the public contact form. Written only by '
  'submit_contact_message() — there is deliberately no insert policy. Holds no '
  'IP, no user-agent and no fingerprint: someone asking a pre-sales question '
  'is not a suspect.';

create index if not exists idx_contact_messages_created
  on public.contact_messages(created_at desc);

alter table public.contact_messages enable row level security;

-- No policy whatsoever. `anon` can neither read nor insert; the security
-- definer function bypasses RLS, and the service role reads for triage.

/**
 * Attempt log, used only to enforce the rate limits.
 *
 * Keyed by a hash of the email, never the address itself: this is a
 * throwaway counter, so keeping readable addresses in it would mean storing
 * personal data for no purpose. md5 is deliberate — there is nothing
 * cryptographic to protect here, we only need to group attempts, and it
 * avoids depending on pgcrypto's schema placement.
 */
create table if not exists public.contact_attempts (
  id bigint generated by default as identity primary key,
  email_hash text not null,
  attempted_at timestamptz default timezone('utc'::text, now()) not null
);

comment on table public.contact_attempts is
  'One row per accepted contact submission, for rate limiting only. No IP, no '
  'message content, and the email only as an md5 hash.';

create index if not exists idx_contact_attempts_window
  on public.contact_attempts(attempted_at desc);
create index if not exists idx_contact_attempts_email
  on public.contact_attempts(email_hash, attempted_at desc);

alter table public.contact_attempts enable row level security;
-- No policy: only the security definer function touches this table. An
-- anonymous caller must not be able to read the log or clear it by deleting.

/**
 * The rate limits, split out so they can be reasoned about alone.
 *
 * Two windows, because they stop different things:
 *   - 60 per 10 minutes globally caps a flood even when it is spread over
 *     thousands of IPs, which a per-IP limit cannot do;
 *   - 3 per hour per email stops a bot hammering under one identity without
 *     penalising everybody else.
 *
 * The global window is a shared ceiling, so under attack a real visitor can be
 * refused for a few minutes. That is the price of storing no IP; the contact
 * page always shows the email address in clear as a way through.
 *
 * Returns true when the call is allowed. Does NOT record — the caller records
 * only once the insert succeeded.
 */
create or replace function public.check_contact_rate(p_email_hash text)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  v_global int;
  v_email int;
begin
  select count(*) into v_global
  from public.contact_attempts
  where attempted_at > now() - interval '10 minutes';

  if v_global >= 60 then
    return false;
  end if;

  select count(*) into v_email
  from public.contact_attempts
  where email_hash = p_email_hash
    and attempted_at > now() - interval '1 hour';

  if v_email >= 3 then
    return false;
  end if;

  return true;
end;
$$;

revoke all on function public.check_contact_rate(text) from public;
-- Not granted to anon: only submit_contact_message calls it, and that one is
-- security definer so it runs with the owner's rights.

/**
 * The only way to write a contact message.
 *
 * Validation is duplicated from the TypeScript action on purpose: the
 * TypeScript is not on the path of a caller who talks to PostgREST directly.
 *
 * Returns a bare boolean, so a refusal never says WHICH bound was hit or
 * whether the limit or the validation rejected it. An attacker learns nothing.
 */
create or replace function public.submit_contact_message(
  p_name text,
  p_email text,
  p_subject text,
  p_message text,
  p_locale text
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  v_name text := trim(coalesce(p_name, ''));
  v_email text := lower(trim(coalesce(p_email, '')));
  v_message text := trim(coalesce(p_message, ''));
  v_locale text := trim(coalesce(p_locale, ''));
  v_hash text;
begin
  if char_length(v_name) < 1 or char_length(v_name) > 80 then
    return false;
  end if;

  if char_length(v_email) < 3 or char_length(v_email) > 160
     or v_email !~ '^[^@[:space:]]+@[^@[:space:].]+\.[a-z]{2,}$' then
    return false;
  end if;

  if p_subject is null or p_subject not in
     ('avant-achat', 'ma-commande', 'technique', 'sur-mesure', 'autre') then
    return false;
  end if;

  if char_length(v_message) < 10 or char_length(v_message) > 2000 then
    return false;
  end if;

  if char_length(v_locale) < 2 or char_length(v_locale) > 5 then
    return false;
  end if;

  v_hash := md5(v_email);

  if not public.check_contact_rate(v_hash) then
    return false;
  end if;

  insert into public.contact_messages (name, email, subject, message, locale)
  values (v_name, v_email, p_subject, v_message, v_locale);

  insert into public.contact_attempts (email_hash) values (v_hash);

  -- Opportunistic cleanup on roughly one call in twenty, so the log cannot
  -- grow without bound and no cron job is needed. Cheap thanks to the index.
  if random() < 0.05 then
    delete from public.contact_attempts
    where attempted_at < now() - interval '2 hours';
  end if;

  return true;
end;
$$;

revoke all on function public.submit_contact_message(text, text, text, text, text) from public;
grant execute on function public.submit_contact_message(text, text, text, text, text) to anon;

comment on function public.submit_contact_message(text, text, text, text, text) is
  'Security-definer RPC backing the public contact form: the only path by '
  'which an anonymous visitor can write a contact message. Validates and '
  'bounds every field, enforces 60 submissions per 10 minutes globally and 3 '
  'per hour per email, and returns a bare boolean so a refusal reveals '
  'nothing. Do not add an insert policy to contact_messages — see the header '
  'of this migration for why.';
