-- Close the guest-facing RSVP area, which until now ran on the service role.
--
-- `dashboard/src/actions/rsvp-actions.ts` reached the database with
-- SUPABASE_SERVICE_ROLE_KEY and no authentication at all, taking `wedding_id`
-- straight from the browser. The service role bypasses RLS by construction, so
-- the owner-only policies on `households` and `guests` (full_db_reset.sql:133
-- and :171) never applied to that path. Anyone could:
--
--   * read every household of any wedding, with `select("*, guests(*)")` —
--     email, phone, address, message_to_couple and `magic_link_token` included;
--   * write RSVP answers into any household of any wedding;
--   * insert households and guests into any wedding.
--
-- The fix follows the shape this project already chose for the seating search
-- in `20260903110000_guest_search_rate_limit.sql`: a security-definer RPC is
-- the only path to guest data, with the column list, the row cap and the rate
-- limit inside the database rather than in the Next.js action. A limit written
-- in the action would be bypassed by calling PostgREST directly with the anon
-- key, which is public.
--
-- Two defects of that earlier migration are deliberately not repeated here:
--   * its rate-limit window is per wedding, so 30 requests lock out every real
--     guest of that wedding. Here the window is per (wedding, caller bucket).
--   * it interpolates the query into `like` without escaping, so a `%` matches
--     everything and defeats the 2-character minimum. Here `%` and `_` are
--     escaped before use.

-- ── Rate limiting ─────────────────────────────────────────────────────────
--
-- Postgres cannot see the client's IP, and inventing a per-guest identifier
-- would mean logging something about people who have done nothing wrong (the
-- reasoning of 20260903110000 that this migration keeps). The compromise is a
-- caller-supplied opaque bucket: the action derives it from the request, so a
-- flood from one source is counted separately from a real guest on their
-- phone. It is not a security boundary on its own — a determined attacker
-- rotates it — which is why the column whitelist and the row cap below do the
-- real work. It exists to stop the cheap enumeration run, and to make sure one
-- abuser cannot lock out an entire wedding.

create table if not exists public.rsvp_attempts (
  id bigint generated by default as identity primary key,
  wedding_id uuid references public.weddings(id) on delete cascade not null,
  -- sha256 hex of a per-request value, never the value itself.
  caller_bucket text not null,
  kind text not null check (kind in ('search', 'write')),
  attempted_at timestamptz default timezone('utc'::text, now()) not null
);

comment on table public.rsvp_attempts is
  'One row per public RSVP call, used only for rate limiting. Holds no query '
  'text, no IP and no name — only an opaque hashed bucket supplied by the '
  'caller, so that one abuser cannot lock out a whole wedding.';

create index if not exists idx_rsvp_attempts_window
  on public.rsvp_attempts(wedding_id, caller_bucket, kind, attempted_at desc);

alter table public.rsvp_attempts enable row level security;

-- No policy: only the security-definer functions below touch this table, and
-- they bypass RLS. An anonymous caller must not be able to read the log, nor
-- to clear it by deleting rows.

create or replace function public.check_rsvp_rate(
  p_wedding_id uuid,
  p_bucket text,
  p_kind text,
  p_limit int,
  p_window interval
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  v_recent int;
begin
  select count(*) into v_recent
  from public.rsvp_attempts
  where wedding_id = p_wedding_id
    and caller_bucket = p_bucket
    and kind = p_kind
    and attempted_at > now() - p_window;

  if v_recent >= p_limit then
    return false;
  end if;

  insert into public.rsvp_attempts (wedding_id, caller_bucket, kind)
  values (p_wedding_id, p_bucket, p_kind);

  -- Opportunistic cleanup on roughly one call in twenty, so the table cannot
  -- grow without bound and no cron job is needed.
  if random() < 0.05 then
    delete from public.rsvp_attempts
    where attempted_at < now() - interval '1 day';
  end if;

  return true;
end;
$$;

revoke all on function public.check_rsvp_rate(uuid, text, text, int, interval) from public;

-- ── 1. Resolve a wedding code ─────────────────────────────────────────────
--
-- Replaces the service-role read of `settings` joined to `profiles`. Returns
-- only what the entry screen prints: the wedding id and the couple's display
-- names. `wedding_code` is not echoed back, and nothing else about the
-- settings row leaves the database.
--
-- The code is the only secret protecting the RSVP area, so guessing must stay
-- expensive: 20 attempts per bucket per 10 minutes. Note that `wedding_code`
-- carries no unique constraint (full_db_reset.sql:83) — `limit 1` here mirrors
-- the previous `.single()` without raising when two couples collide, which is
-- a separate bug tracked in the audit note.

create or replace function public.resolve_wedding_code(
  p_code text,
  p_bucket text
)
returns table (
  wedding_id uuid,
  couple_names text
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_wedding_id uuid;
begin
  if p_code is null or length(trim(p_code)) < 4 then
    return;
  end if;

  select s.wedding_id into v_wedding_id
  from public.settings s
  where upper(trim(s.wedding_code)) = upper(trim(p_code))
  limit 1;

  if v_wedding_id is null then
    -- Count failures too, otherwise brute force is free.
    perform public.check_rsvp_rate(
      '00000000-0000-0000-0000-000000000000'::uuid, p_bucket, 'search', 20, interval '10 minutes'
    );
    return;
  end if;

  if not public.check_rsvp_rate(v_wedding_id, p_bucket, 'search', 20, interval '10 minutes') then
    return;
  end if;

  return query
  select
    v_wedding_id,
    concat_ws(' & ', nullif(p.first_name, ''), nullif(p.partner_name, ''))
  from public.weddings w
  join public.profiles p on p.id = w.user_id
  where w.id = v_wedding_id;
end;
$$;

comment on function public.resolve_wedding_code(text, text) is
  'Security-definer RPC turning a wedding code into a wedding id and the '
  'couple''s display names, for the public RSVP entry screen. Returns nothing '
  'else about the settings row, and rate-limits failures so the code cannot be '
  'brute forced.';

-- ── 2. Search a household ─────────────────────────────────────────────────
--
-- Replaces `select("*, guests(*)")`. The columns below are exactly what
-- `dashboard/src/app/[locale]/rsvp/page.tsx` renders: household id and name,
-- and per guest the id, names, status and dietary note it lets people edit.
-- `magic_link_token`, `email`, `phone`, `address` and `message_to_couple`
-- never leave the database on this path.
--
-- Guests come back as JSON so one call still returns the household with its
-- members, the way the page expects.

create or replace function public.search_rsvp_household(
  p_wedding_id uuid,
  p_query text,
  p_bucket text
)
returns table (
  id uuid,
  name text,
  status text,
  guests jsonb
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_query text;
begin
  if p_wedding_id is null or length(trim(p_query)) < 2 then
    return;
  end if;

  if not public.check_rsvp_rate(p_wedding_id, p_bucket, 'search', 30, interval '10 minutes') then
    return;
  end if;

  -- Escape the LIKE wildcards before interpolating: without this a single `%`
  -- satisfies the 2-character minimum and returns every household, which is
  -- the defect still present in search_guest_table.
  v_query := replace(replace(replace(lower(trim(p_query)), '\', '\\'), '%', '\%'), '_', '\_');

  return query
  select
    h.id,
    h.name,
    h.status,
    coalesce(
      (
        select jsonb_agg(
          jsonb_build_object(
            'id', g.id,
            'first_name', g.first_name,
            'last_name', g.last_name,
            'status', g.status,
            'dietary_requirements', g.dietary_requirements
          )
          order by g.first_name
        )
        from public.guests g
        where g.household_id = h.id
      ),
      '[]'::jsonb
    ) as guests
  from public.households h
  where h.wedding_id = p_wedding_id
    and lower(h.name) like '%' || v_query || '%' escape '\'
  order by h.name
  limit 5;
end;
$$;

comment on function public.search_rsvp_household(uuid, text, text) is
  'Security-definer RPC backing the public RSVP household search. The only '
  'path by which an anonymous guest reaches household data: a 2-character '
  'minimum with LIKE wildcards escaped, a 5-row cap, a rate limit, and a '
  'strict column whitelist that excludes magic_link_token, email, phone, '
  'address and message_to_couple. Do not widen the column list.';

-- ── 3. Record an RSVP answer ──────────────────────────────────────────────
--
-- Replaces the service-role update. The household must belong to the wedding
-- the caller resolved, and each guest must belong to that household — checked
-- inside the function rather than trusted from the caller's `.eq()` chain.
--
-- `p_guests` is `[{id, status, dietary_requirements}, …]`. Statuses are
-- constrained to the values the `guests` check constraint allows, so a forged
-- value fails loudly instead of writing something the dashboard cannot read.

create or replace function public.submit_rsvp_household(
  p_wedding_id uuid,
  p_household_id uuid,
  p_email text,
  p_song text,
  p_transport text,
  p_message text,
  p_guests jsonb,
  p_bucket text
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  v_exists boolean;
  v_guest jsonb;
begin
  select exists (
    select 1 from public.households
    where id = p_household_id and wedding_id = p_wedding_id
  ) into v_exists;

  if not v_exists then
    return false;
  end if;

  if not public.check_rsvp_rate(p_wedding_id, p_bucket, 'write', 20, interval '10 minutes') then
    return false;
  end if;

  update public.households
  set
    email = coalesce(nullif(trim(p_email), ''), email),
    song_request = left(p_song, 500),
    transportation = left(p_transport, 500),
    message_to_couple = left(p_message, 2000),
    status = 'confirmed'
  where id = p_household_id
    and wedding_id = p_wedding_id;

  for v_guest in select * from jsonb_array_elements(coalesce(p_guests, '[]'::jsonb))
  loop
    update public.guests
    set
      status = case
        when v_guest->>'status' in ('pending', 'confirmed', 'declined')
          then v_guest->>'status'
        else status
      end,
      dietary_requirements = left(v_guest->>'dietary_requirements', 500)
    where id = (v_guest->>'id')::uuid
      -- Both gates matter: the guest must sit in this household AND in this
      -- wedding, so a forged guest id from another couple is a no-op.
      and household_id = p_household_id
      and wedding_id = p_wedding_id;
  end loop;

  return true;
end;
$$;

comment on function public.submit_rsvp_household(uuid, uuid, text, text, text, text, jsonb, text) is
  'Security-definer RPC recording a guest RSVP. Verifies the household belongs '
  'to the wedding and each guest to that household before writing, caps free '
  'text, and constrains status to the values the check constraint allows.';

-- ── 4. Register a new household (open mode) ───────────────────────────────
--
-- Replaces the service-role insert. Two conditions the old code never checked:
-- the wedding must exist, and `settings.rsvp_mode` must be 'open'. That column
-- has been in the schema since the first migration (full_db_reset.sql:81) with
-- a default of 'closed', and nothing has ever read it — so self-registration
-- was in fact available on every wedding, including those that never opened it.
--
-- Because the default is 'closed', treating it strictly would silently switch
-- off a feature couples may be using today. The audit note records this; the
-- behaviour here is the honest reading of the column, and the dashboard needs
-- a toggle for it before this is deployed to couples relying on open mode.

create or replace function public.register_rsvp_household(
  p_wedding_id uuid,
  p_name text,
  p_email text,
  p_song text,
  p_transport text,
  p_message text,
  p_guests jsonb,
  p_bucket text
)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_mode text;
  v_household_id uuid;
  v_guest jsonb;
  v_count int := 0;
begin
  if p_wedding_id is null or length(trim(coalesce(p_name, ''))) < 2 then
    return null;
  end if;

  select rsvp_mode into v_mode
  from public.settings
  where wedding_id = p_wedding_id;

  if v_mode is distinct from 'open' then
    return null;
  end if;

  if not public.check_rsvp_rate(p_wedding_id, p_bucket, 'write', 5, interval '1 hour') then
    return null;
  end if;

  insert into public.households (
    wedding_id, name, email, song_request, transportation,
    message_to_couple, status, source
  )
  values (
    p_wedding_id,
    left(trim(p_name), 200),
    nullif(trim(coalesce(p_email, '')), ''),
    left(p_song, 500),
    left(p_transport, 500),
    left(p_message, 2000),
    'pending',
    'public'
  )
  returning id into v_household_id;

  for v_guest in select * from jsonb_array_elements(coalesce(p_guests, '[]'::jsonb))
  loop
    exit when v_count >= 20;
    if length(trim(coalesce(v_guest->>'first_name', ''))) > 0 then
      insert into public.guests (
        wedding_id, household_id, first_name, last_name,
        status, dietary_requirements
      )
      values (
        p_wedding_id,
        v_household_id,
        left(trim(v_guest->>'first_name'), 100),
        left(coalesce(nullif(trim(v_guest->>'last_name'), ''), '.'), 100),
        case
          when v_guest->>'status' in ('pending', 'confirmed', 'declined')
            then v_guest->>'status'
          else 'confirmed'
        end,
        left(v_guest->>'dietary_requirements', 500)
      );
      v_count := v_count + 1;
    end if;
  end loop;

  -- Household and guests are written in one function call, so a failure on the
  -- guest loop rolls the household back with it. The old code inserted the
  -- household first and logged "we don't rollback for now" when the guests
  -- failed, leaving empty households behind.
  return v_household_id;
end;
$$;

comment on function public.register_rsvp_household(uuid, text, text, text, text, text, jsonb, text) is
  'Security-definer RPC for open-mode self-registration. Honours '
  'settings.rsvp_mode (previously never read), caps the party at 20 guests, '
  'rate-limits to 5 registrations per bucket per hour, and is atomic: a failed '
  'guest insert rolls back the household.';

-- ── Grants ────────────────────────────────────────────────────────────────
--
-- These four are the entire public surface of the RSVP area. The underlying
-- tables stay owner-only: nothing here grants anon any direct table access.

grant execute on function public.resolve_wedding_code(text, text) to anon, authenticated;
grant execute on function public.search_rsvp_household(uuid, text, text) to anon, authenticated;
grant execute on function public.submit_rsvp_household(uuid, uuid, text, text, text, text, jsonb, text) to anon, authenticated;
grant execute on function public.register_rsvp_household(uuid, text, text, text, text, text, jsonb, text) to anon, authenticated;
