-- Invoicing.
--
-- French law requires an invoice per sale, numbered in an unbroken, strictly
-- increasing sequence with no gaps and no reuse (art. 242 nonies A, annexe II
-- du CGI). Two things follow from that, and both are why this is a migration
-- rather than application code:
--
--   1. The number must be allocated atomically. Two concurrent webhook
--      deliveries computing "max + 1" in JavaScript would mint the same
--      number, so allocation happens inside Postgres under a row lock.
--   2. A number, once allocated, is never rolled back or reused. Sequences are
--      per calendar year, which is the convention French accounting expects.

-- ── Counter, one row per year ──────────────────────────────────────────────
create table if not exists public.invoice_counters (
  year integer primary key,
  last_number integer not null default 0
);

alter table public.invoice_counters enable row level security;

-- Service role only: invoice numbering is never touched from the browser.
create policy "service_role_only" on public.invoice_counters
  using (auth.role() = 'service_role');

-- ── Invoices ───────────────────────────────────────────────────────────────
create table if not exists public.invoices (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references auth.users not null,
  -- One invoice per payment. The unique constraint is the idempotency guard:
  -- Stripe redelivers `payment_intent.succeeded`, and a retry must find the
  -- existing invoice rather than burn a second number for the same sale.
  stripe_payment_intent_id text unique not null,
  -- Human-readable, e.g. "FA-2026-0001". Unique across all years.
  invoice_number text unique not null,
  issued_at timestamptz default now() not null,

  -- Amounts in cents, mirroring how Stripe and `billing` store them.
  total_cents integer not null,
  -- Under the franchise en base these equal total_cents and 0 respectively.
  subtotal_cents integer not null,
  vat_cents integer not null default 0,
  vat_rate numeric(4, 3) not null default 0,
  currency text not null default 'eur',

  -- Buyer identity, frozen at issue time: an invoice must keep showing what
  -- was true on the day it was issued, even if the couple later edit their
  -- profile. Denormalised on purpose.
  customer_email text not null,
  customer_name text,

  -- Line items as billed, so the PDF can be regenerated byte-identically
  -- without recomputing prices that may have changed since.
  line_items jsonb not null default '[]'::jsonb,

  -- Supabase Storage path of the rendered PDF, once it exists.
  pdf_path text,

  created_at timestamptz default now() not null
);

alter table public.invoices enable row level security;

-- Couples read their own invoices from the dashboard; nobody writes from the
-- browser — issuing is a service-role operation in the Stripe webhook.
create policy "Users can view own invoices" on public.invoices
  for select using (auth.uid() = user_id);

create index if not exists invoices_user_id_idx on public.invoices (user_id);
create index if not exists invoices_issued_at_idx on public.invoices (issued_at desc);

-- ── Atomic number allocation ───────────────────────────────────────────────
--
-- `insert … on conflict do update` takes a row-level lock on the counter, so
-- concurrent callers serialise here instead of racing. Returns the formatted
-- number, e.g. "FA-2026-0007".
create or replace function public.next_invoice_number()
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  current_year integer := extract(year from now() at time zone 'utc')::integer;
  next_value integer;
begin
  insert into public.invoice_counters (year, last_number)
    values (current_year, 1)
  on conflict (year)
    do update set last_number = public.invoice_counters.last_number + 1
  returning last_number into next_value;

  return 'FA-' || current_year || '-' || lpad(next_value::text, 4, '0');
end;
$$;

-- Callable by the service role only; the browser never mints numbers.
revoke all on function public.next_invoice_number() from public, anon, authenticated;

-- ── PDF storage ────────────────────────────────────────────────────────────
--
-- Private, unlike the media buckets: an invoice carries the customer's name
-- and address, so it is served through short-lived signed URLs rather than a
-- public path.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('invoices', 'invoices', false, 5242880, array['application/pdf'])
on conflict (id) do nothing;

-- Objects are keyed "<user_id>/<invoice_number>.pdf", so the first path
-- segment scopes a couple to their own invoices.
create policy "Users can read own invoices pdf"
on storage.objects for select
to authenticated
using (
  bucket_id = 'invoices'
  and (storage.foldername(name))[1] = auth.uid()::text
);
